#!/bin/sh
mkdir -p /tmp/tailscale

/var/runtime/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 &

sleep 2

/var/runtime/tailscale up --auth-key=${TAILSCALE_AUTHKEY} --hostname=fb-scraper-lambda --exit-node=${EXIT_NODE} --accept-risk=linux-strict-rp-filter

echo "Tailscale connected to Exit Node"

export ALL_PROXY=socks5://localhost:1055/
export http_proxy=http://localhost:1055/
export https_proxy=http://localhost:1055/

exec /var/lang/bin/node /var/runtime/index.mjs $1
